"""Changed relationship between building and organization

Revision ID: 9e58c686be5d
Revises: 2d9021f6cc11
Create Date: 2025-10-23 05:04:24.612611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e58c686be5d'
down_revision: Union[str, Sequence[str], None] = '2d9021f6cc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('organizations_building_id_key'), 'organizations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('organizations_building_id_key'), 'organizations', ['building_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
